# const.py

GENELEC_GLM_VID: int = 0x1781
GENELEC_GLM_PID: int = 0x0E39


# Command IDs as GLM appears to use them
CID_RACE: int = 0xFE
CID_SET_RID: int = 0x02
CID_SOFT_RESET: int = 0x03
CID_STAY_ONLINE: int = 0x04
CID_TEST_SIGNALS: int
CID_WRITE_FLASH: int
CID_READ_FLASH: int
CID_POLL: int = 0x08
CID_0x09: int = 0x09
CID_VOL_A: int
CID_VOL_B: int
CID_STANDBY: int
CID_SET_INPUT: int = 0x0D
CID_SET_EMPHASIS: int
CID_MINMAX_SPL: int
CID_DSP_COEFF: int  # might be 0x10
CID_SET_LFE: int
CID_LFE_QUERY: int
CID_2WAY_UPGRADE: int
CID_VOLUME_ANAL: int
CID_SUB_DAISY_CHAIN: int
CID_NET_SETTINGS: int  # might be 0x17
CID_BASS_MANAGE: int
CID_BAR_CODE: int = 0x19
CID_BOOT: int
CID_VOLUME_IF: int
CID_PEEK: int
CID_POKE: int
CID_0x2E: int
CID_VOLUME_GLM: int = 0x1F
CID_DSP_PEEK_POKE: int
CID_HARDWARE_QUERY: int = 0x22
CID_SOFTWARE_QUERY: int
CID_START_VOLUME: int
CID_DA_TYPE_QUERY: int
CID_INPUT_QUERY: int
CID_DIG_AUD_QUERY: int
CID_SWITCH_HP: int
CID_SWITCH_LP: int
CID_BYPASS_QUERY: int = 0x2B  # FIXME: guesswork
CID_GROUP: int
CID_UID_QUERY: int
CID_SWITCH_BYPASS: int
CID_FIRMWARE_UPDATE: int
CID_ERASE_FLASH: int
CID_LOAD_DSP_CODE: int
CID_UPGRADE_SOFT: int
CID_STORE_USER_PARS: int  # might be 0x33
CID_RESTORE_USER_PARS: int
CID_STORE_CALIBRATION: int
CID_OPEN_FACTORY_LOCK: int
CID_GAINRIDE: int
CID_PROTECTION: int
CID_SOFTWARE_QUERY2: int = 0x39
CID_ISS: int  # might be 0x3A, see CID_WAKEUP
CID_BASS_MANAGE_XO: int = 0x3B
CID_BASS_AFILTER: int = 0x3C  # FIXME: guesswork
CID_BASS_BYPASS: int = 0x3D  # FIXME: guesswork
CID_LFE_GAIN: int = 0x3E
CID_DSP_PAR: int
CID_SELECT_AUDIO_SOURCE: int = 0x40  # FIXME: guesswork
CID_CLIP: int
CID_DIGISUM_GAIN: int = 0x42  # FIXME: guesswork
CID_TRACE: int
CID_NAMES_USER: int
CID_NAMES_FACTORY: int
CID_BYPASS_FILTERS: int
CID_ETH_MAC_ADDRESS: int
CID_DIPSW: int
CID_COOL_CTRL: int
CID_WAKEUP: int = 0x3A

# These constant names were made up:
CID_MIC_SERIAL: int = 0x51

GNET_ACK: int = 0x09  # FIXME: guesswork
GNET_NACK: int
GNET_NOCANDO: int
GNET_TIMEOUT: int = 0x7E  # FIXME: guesswork

GNET_MULTICAST_ADDR: int = 0xF0
GNET_BROADCAST_ADDR: int = 0xFF

GNET_TERM: int = 0x7E
GNET_MESSAGE_MAX_LENGTH: int = 64

# LED colors
LED_GREEN = 0
LED_RED = 1
LED_OFF = 2
LED_YELLOW = 3

# Defaults
DEFAULT_XO_FREQ = 85
